theme: jekyll-theme-minimal
name: Vue Boilerplate

description: Vue BoilerPlate with babel7/weback4

avatar: https://labtocat.github.io/vue-boilerplate/src/assets/logo.png
title-img: https://labtocat.github.io/vue-boilerplate/src/assets/logo.png
logo : https://labtocat.github.io/vue-boilerplate/src/assets/logo.png
